name = "xcu-trans-router"
main = "xcu-trans-router.js"
compatibility_date = "2026-05-14"

routes = [
  { pattern = "xcu.ai/trans*", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/trans-login", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/trans-logout", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/api-proxy/api/openai/realtime-translation/session", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/api-proxy/api/openai/reply-translation", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/api-proxy/api/openai/reply-speech", zone_name = "xcu.ai" },
  { pattern = "xcu.ai/api-proxy/api/openai/text-translation", zone_name = "xcu.ai" }
]
